# Generated by Django 4.2.7 on 2023-11-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
